[package]
name = "xtask"
edition = "2021"
version.workspace = true

[dependencies]
color-eyre = "0.6"
xshell = "0.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [ "env-filter" ] }
