name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  pull-requests: read
jobs:
  main:
    name: Validate PR title
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
